# Backend
# Can be:
# - "local" (run containers on the same machine)
# - or an address to a distant manually-launched backend, in the form "tcp://host.be:3000", "udp://host.be:3000" or "ipc:///path/to/socket"
backend: local

# Logging level
log_level: INFO

# Only for backend: local
local-config:
    # debug_host: localhost  # host that will be indicated to users when they want to use the task remote debug feature. Automatically guessed by
                             # default
    debug_ports: 64000-64100 #port range use for remote debug feature

# MongoDB options
mongo_opt:
    host: localhost
    database: INGInious

# Location of the task directory
tasks_directory: ./inginious/tasks

# Use single minified javascript file (production) or multiple files (dev) ?
use_minified_js: true

# LTI consumer keys
lti:
    # Each entry correspond to the consumer key
    key1:
        # Passphrase corresponding to key 'key1'
        secret: password1
    key2:
        secret: password2
        # Key 'key2' is only authorized to access the following course list, identified by their course id
        courses: 
            - mycourse

# LTI field to use for username, by default 'user_id'
# Use 'ext_user_username' only if your LMS supports it.
lti_user_name: 'user_id'

# Location of the download directory
download_directory: ./download